version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli@15
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
  files:
    - '**/*'
  base-directory: dist/my-app  # Update this to the correct path

cache:
  paths:
    - 'node_modules/**/*'